### ISSUE TITLE
Тестирование.md

### ISSUE THREAD

**Issue by designerror** [LLlKuIIeP/Virtual-FS#1]
**Тестирование**

*Ссылки для ознакомления*
- [Отличие стилей тестирования](http://habrahabr.ru/post/107262/)
- [Catch](https://github.com/philsquared/Catch) - фреймворк для тестирования (поддерживающий стиль написания bdd)

**Comment by LLlKuIIeP** [comment]
Добрый вечер.

В репозитории GoogleTest_TDD сделал задачу используя [Google testing framework (gtest)](http://habrahabr.ru/post/119090/).

 В планах сделать другую задачу используя [Catch](https://github.com/philsquared/Catch/blob/master/README.md) - фреймворк, выполненная задача будет в соответствующем репозитории.
