### ISSUE TITLE
Литература

### ISSUE THREAD

**Issue by designerror** [LLlKuIIeP/Virtual-FS#3]
- Чистый код. Создание, анализ и рефакторинг. *Мартин Роберт.*
- Программирование. Принципы и практика использования C++. *Бьярне Страуструп.*

**Comment by LLlKuIIeP** [comment]
# Прочитал

* Мартин Роберт "Чистый код. Создание, анализ и рефакторинг" до главы 16.

* Бьярне Страуструп "Программирование. Принципы и практика использования C++" главы:
    1. Компьютеры, люди и программирование
    2. Hello, World!
    3. Объекты, типы и значения

**Comment by designerror** [comment]
Так держать =)

**Comment by LLlKuIIeP** [comment]
* Мартин Роберт "Чистый код. Создание, анализ и рефакторинг" дочитал. 

* Бьярне Страуструп "Программирование. Принципы и практика использования C++" главы:
    4. Вычисления
    5. Ошибки
    6. Создание программ

* Сделал несколько упражнений (*из книги Б. Страуструпа*) методом TDD используя Catch - фреймворк. Тесты написал в BDD стиле: `SCENARIO`, `GIVEN`, `WHEN`, `THEN`.

**Comment by LLlKuIIeP** [comment]
* Бьярне Страуструп "Программирование. Принципы и практика использования C++" главы:
    * 7.Завершение программы
    * 8.Технические детали: функции и прочее
    * 9.Технические детали: классы и прочее

**Comment by LLlKuIIeP** [comment]
Доброго времени суток.

* Бьярне Страуструп "Программирование. Принципы и практика использования C++" глава 10.Потоки ввода и вывода.

Также немного изменил код задачи "Результаты олимпиады" в репозитории [Yandex_Catch_BDD](https://github.com/LLlKuIIeP/Yandex_Catch_BDD).

**Comment by LLlKuIIeP** [comment]
Доброго времени суток.

После получения диплома на руки немного отдохнул.

* *Бьярне Страуструп* "Программирование. Принципы и практика использования C++" главы с 11 по 14 включительно.

Нашел одну интересную и не сложную задачу, репозиторий [Eratosthenes](https://github.com/LLlKuIIeP/Eratosthenes).

**Comment by LLlKuIIeP** [comment]
*Бьярне Страуструп* "Программирование. Принципы и практика использования C++" глава 15.

Плюс репозиторий [List](https://github.com/LLlKuIIeP/List).

**Comment by LLlKuIIeP** [comment]
*Бьярне Страуструп* "Программирование. Принципы и практика использования C++" главы 16 и 17.

**Comment by designerror** [comment]
get  your email.

**Comment by LLlKuIIeP** [comment]
Добрый день.

В интернете нашел книгу *Голуб А. И.* "Веревка достаточной длины, чтобы... выстрелить себе в ногу", думаю её почитать.

*Бьярне Страуструп* "Программирование. Принципы и практика использования C++" главы 18 и 19.

**Comment by designerror** [comment]
get your email.

**Comment by LLlKuIIeP** [comment]
Сказали позвонить в четверг в 14:00.
